SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[People](
	[PersonID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nchar](32) NOT NULL,
	[LastLogin] [datetime] NULL,
 CONSTRAINT [PK_People] PRIMARY KEY CLUSTERED 
(
	[PersonID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE PROCEDURE [dbo].[INS_Person]
	@Name nchar(32)
AS
BEGIN
	SET NOCOUNT ON;

    INSERT INTO [People] (Name, LastLogin) VALUES (@Name, GETDATE());
    
    SELECT SCOPE_IDENTITY() AS PersonID;
END
